# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kparts': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/karchive': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/kinit': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kguiaddons': '@stable'
    'frameworks/kactivities': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kdesu': '@stable'
